export const apiRoutes = [
  "GET /api/jobs",
  "POST /api/jobs",
  "GET /api/jobs/:id",
  "PATCH /api/jobs/:id",
  "GET /api/companies",
  "GET /api/companies/:id",
  "GET /api/staffing-leads",
  "POST /api/staffing-leads",
  "PATCH /api/staffing-leads/:id",
  "GET /api/direct-leads",
  "POST /api/direct-leads",
  "PATCH /api/direct-leads/:id",
  "GET /api/outreach-tasks",
  "POST /api/outreach-tasks",
  "PATCH /api/outreach-tasks/:id",
  "GET /api/sources",
  "POST /api/sources",
  "PATCH /api/sources/:id",
  "POST /api/sources/:id/run",
  "POST /api/import/csv",
  "GET /api/analytics/overview",
];
